packages:
  - "packages/*"
  - "apps/*"

catalogs:
  default:
    react: ^19.2.3
    react-dom: ^19.2.3
    next: "16.1.6"
    typescript: ^5.7.2
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    "@types/node": ^22.0.0
    tailwindcss: ^4.0.0
    "@tailwindcss/postcss": ^4.0.0
    date-fns: ^4.1.0

    axios: ^1.11.0
    gray-matter: ^4.0.3
    mysql2: ^3.17.4
    keycloak-js: ^26.2.3
    lucide-react: ^0.563.0
    antd: ^5.26.7
    express: ^5.1.0
    cors: ^2.8.5
    multer: ^2.0.2
    qs: ^6.14.0
    uuid: ^13.0.0
    jose: ^6.1.0
    zustand: ^5.0.0
