packages:
  - "packages/*"
  - "apps/*"

catalogs:
  default:
    react: ^19.2.3
    react-dom: ^19.2.3
    next: "16.1.6"
    typescript: ^5.7.2
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    "@types/node": ^22.0.0
    tailwindcss: ^4.0.0
    "@tailwindcss/postcss": ^4.0.0
