packages:
  - packages/*
  - apps/*

catalogs:
  default:
    '@tailwindcss/postcss': ^4.0.0
    '@types/node': ^22.0.0
    '@types/react': ^19.0.0
    '@types/react-dom': ^19.0.0
    antd: ^6.0.0
    axios: ^1.11.0
    cors: ^2.8.5
    date-fns: ^4.1.0
    express: ^5.1.0
    gray-matter: ^4.0.3
    jose: ^6.1.0
    keycloak-js: ^26.2.3
    lucide-react: ^0.563.0
    multer: ^2.0.2
    mysql2: ^3.17.4
    next: 16.1.6
    qs: ^6.14.0
    react: ^19.2.3
    react-dom: ^19.2.3
    tailwindcss: ^4.0.0
    typescript: ^5.7.2
    zustand: ^5.0.0

injectWorkspacePackages: true
